[package]
name = "pi_cowlist"
version = "0.1.0"
authors = ["suncy <530739162@qq.com>"]
edition = "2021"
description = "Linked list copied on write"
repository = "https://github.com/GaiaWorld/pi_cowlist.git"
license = "MIT OR Apache-2.0"
keywords = ["pi", "pi_cowlist", "Linklist"]